version: "3.8"

services:
  db:
    image: postgres:alpine
    container_name: 5ab4e17c60aa
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: pythonscraping_db
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
